version: '3.4'

services:
  ipmanagement:
    # image: ipmanagement
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: