version: '3.4'

services:
  ipmanagement:
    # image: ipmanagement
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: syokinet
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: